"""Updated Project header to include date created and date modified

Revision ID: 25f921d88ae1
Revises: 2e848e3e7a38
Create Date: 2019-05-17 16:03:04.148956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f921d88ae1'
down_revision = '2e848e3e7a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectdetails', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('projectdetails', sa.Column('date_last_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectdetails', 'date_last_update')
    op.drop_column('projectdetails', 'date_created')
    # ### end Alembic commands ###
