"""empty message

Revision ID: 4f24b7f968a0
Revises: ee9b37e7fe4e
Create Date: 2019-10-16 17:36:00.905018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f24b7f968a0'
down_revision = 'ee9b37e7fe4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_type')
    # ### end Alembic commands ###
