"""Added name data to user relation

Revision ID: 916228766115
Revises: dad8cdacfbf5
Create Date: 2019-05-15 01:29:45.359517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916228766115'
down_revision = 'dad8cdacfbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
