"""Added Slug For Posts

Revision ID: 921b1ff9b498
Revises: 9cf2e1359928
Create Date: 2019-05-31 15:28:30.357699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921b1ff9b498'
down_revision = '9cf2e1359928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
