"""Added Post active state and backref to post

Revision ID: 9cf2e1359928
Revises: 5493e3e47bb3
Create Date: 2019-05-25 00:18:20.965304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf2e1359928'
down_revision = '5493e3e47bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('active_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'active_state')
    # ### end Alembic commands ###
