"""Added active state to project header

Revision ID: defc43323817
Revises: 916228766115
Create Date: 2019-05-15 13:14:19.542311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defc43323817'
down_revision = '916228766115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectheader', sa.Column('active_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectheader', 'active_state')
    # ### end Alembic commands ###
